CREATE EXTERNAL TABLE [emin].[Campus] (
    [Code] NVARCHAR (4000) NULL,
    [Name] NVARCHAR (4000) NULL,
    [Type] NVARCHAR (4000) NULL,
    [Location] NVARCHAR (4000) NULL,
    [ABN] NVARCHAR (4000) NULL,
    [fwLockUser] NVARCHAR (4000) NULL,
    [fwLockTime] DATETIME2 (7) NULL,
    [fwCreatedBy] NVARCHAR (4000) NULL,
    [fwCreated] DATETIME2 (7) NULL,
    [fwUpdatedBy] NVARCHAR (4000) NULL,
    [fwUpdated] DATETIME2 (7) NULL,
    [Currency] NVARCHAR (4000) NULL,
    [ProviderCode] NVARCHAR (4000) NULL,
    [ProviderName] NVARCHAR (4000) NULL,
    [TrainingAuthorityID] NVARCHAR (4000) NULL,
    [AVET_TrainOrgID] NVARCHAR (4000) NULL,
    [AVET_TrainOrgName] NVARCHAR (4000) NULL,
    [AVET_TrainOrgShName] NVARCHAR (4000) NULL,
    [AVET_AddFirstLine] NVARCHAR (4000) NULL,
    [AVET_AddSecondLine] NVARCHAR (4000) NULL,
    [AVET_SubTownLoc] NVARCHAR (4000) NULL,
    [AVET_PCode] NVARCHAR (4000) NULL,
    [AVET_ContName] NVARCHAR (4000) NULL,
    [AVET_PhNum] NVARCHAR (4000) NULL,
    [AVET_FaxNum] NVARCHAR (4000) NULL,
    [AVET_EmailAdd] NVARCHAR (4000) NULL,
    [AVET_TrainTypeID] NVARCHAR (4000) NULL,
    [AVET_State] NVARCHAR (4000) NULL,
    [AVET_TrainAuthorityID] NVARCHAR (4000) NULL,
    [AVET_TrainAuthorityName] NVARCHAR (4000) NULL,
    [AVET_AuthAddFirstLine] NVARCHAR (4000) NULL,
    [AVET_AuthAddSecondLine] NVARCHAR (4000) NULL,
    [AVET_AuthPCode] NVARCHAR (4000) NULL,
    [AVET_AuthState] NVARCHAR (4000) NULL,
    [AVET_AuthContactNAme] NVARCHAR (4000) NULL,
    [AVET_AuthTelephone] NVARCHAR (4000) NULL,
    [AVET_AuthFacsimile] NVARCHAR (4000) NULL,
    [AVET_AuthEmail] NVARCHAR (4000) NULL,
    [AVET_AuthSubTownLoc] NVARCHAR (4000) NULL,
    [notes] NVARCHAR (4000) NULL,
    [SchoolNum] NVARCHAR (4000) NULL,
    [DateLastIncRan] DATETIME2 (7) NULL,
    [DateNextRunOK] DATETIME2 (7) NULL,
    [IncYearMonths] INT NULL,
    [WSDLLocation] NVARCHAR (4000) NULL,
    [CertificateName] NVARCHAR (4000) NULL,
    [CanSubmitElec] INT NULL,
    [Gender] NVARCHAR (4000) NULL,
    [EstDate] DATETIME2 (7) NULL,
    [ClosedDate] DATETIME2 (7) NULL,
    [DataCompliant] BIT NULL,
    [ABNBranchNo] NVARCHAR (4000) NULL,
    [NSN] NVARCHAR (4000) NULL,
    [NCN] NVARCHAR (4000) NULL,
    [StateEduID] NVARCHAR (4000) NULL,
    [CRICOSName] NVARCHAR (4000) NULL,
    [AccreditedName] NVARCHAR (4000) NULL,
    [AdminArea] NVARCHAR (4000) NULL,
    [ServiceArea] NVARCHAR (4000) NULL,
    [AccreditedType] NVARCHAR (4000) NULL,
    [GeoArea] NVARCHAR (4000) NULL,
    [SiteSize] NVARCHAR (4000) NULL,
    [RPropDesc] NVARCHAR (4000) NULL,
    [MapRef] NVARCHAR (4000) NULL,
    [ChurchAffiliation] NVARCHAR (4000) NULL,
    [ChurchAuthority] NVARCHAR (4000) NULL,
    [SchoolSystem] NVARCHAR (4000) NULL,
    [ParishName] NVARCHAR (4000) NULL,
    [ApprovedAuth] NVARCHAR (4000) NULL,
    [MissionStatement] NVARCHAR (4000) NULL,
    [VisionStatement] NVARCHAR (4000) NULL,
    [Motto] NVARCHAR (4000) NULL,
    [WebAddress] NVARCHAR (4000) NULL
)
    WITH (
    DATA_SOURCE = [sds-raw-data_bceaaesdslake2_dfs_core_windows_net],
    LOCATION = N'eMinerva/Campus.parquet',
    FILE_FORMAT = [SynapseParquetFormat],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );
GO

