CREATE EXTERNAL TABLE [emin].[Module] (
    [Code] NVARCHAR (4000) NULL,
    [Name] NVARCHAR (4000) NULL,
    [Faculty] NVARCHAR (4000) NULL,
    [Type] NVARCHAR (4000) NULL,
    [ResultType] NVARCHAR (4000) NULL,
    [TotalMarks] INT NULL,
    [SupervisedHours] INT NULL,
    [CostPerHour] NUMERIC (18, 2) NULL,
    [SubModules] INT NULL,
    [Active] INT NULL,
    [fwLockUser] NVARCHAR (4000) NULL,
    [fwLockTime] DATETIME2 (7) NULL,
    [fwCreatedBy] NVARCHAR (4000) NULL,
    [fwCreated] DATETIME2 (7) NULL,
    [fwUpdatedBy] NVARCHAR (4000) NULL,
    [fwUpdated] DATETIME2 (7) NULL,
    [AVET_ModUnComName] NVARCHAR (4000) NULL,
    [AVET_ModUnCompEdID] NVARCHAR (4000) NULL,
    [AVET_NomHrs] INT NULL,
    [AVET_NomHrsUnsuper] INT NULL,
    [AVET_ModUnComID] NVARCHAR (4000) NULL,
    [AVET_ModUnFlag] NVARCHAR (4000) NULL,
    [AVET_VET] NVARCHAR (4000) NULL,
    [Mapped] INT NULL,
    [AVET_OutcomeTOrg] NVARCHAR (4000) NULL,
    [AVET_FundSourceState] NVARCHAR (4000) NULL,
    [AVET_DeliveryStrategy] NVARCHAR (4000) NULL,
    [AVET_DeliveryType] NVARCHAR (4000) NULL,
    [AVET_FundSourceNat] NVARCHAR (4000) NULL,
    [notes] NVARCHAR (4000) NULL,
    [AVET_ACFEProgCatCode] NVARCHAR (4000) NULL,
    [CodeHE] NVARCHAR (4000) NULL,
    [DisciplineGrp] NVARCHAR (4000) NULL,
    [LearningZone] NVARCHAR (4000) NULL,
    [InstructionMode] NVARCHAR (4000) NULL,
    [NZSubjectCode] NVARCHAR (4000) NULL,
    [Curriculum] NVARCHAR (4000) NULL,
    [SubjectGroup] NVARCHAR (4000) NULL,
    [SchoolCampus] NVARCHAR (4000) NULL,
    [CreditPointsType] NVARCHAR (4000) NULL,
    [CreditPoints] INT NULL,
    [SubjectType] NVARCHAR (4000) NULL,
    [NominalHours] INT NULL,
    [OfferingIdentifier] NVARCHAR (4000) NULL,
    [SubjectIdentifier] NVARCHAR (4000) NULL,
    [AlternateSubjectCode] NVARCHAR (4000) NULL,
    [AlternateSubjectName] NVARCHAR (4000) NULL,
    [AssociatedCosts] NUMERIC (18, 2) NULL,
    [DeliveryType] NVARCHAR (4000) NULL
)
    WITH (
    DATA_SOURCE = [sds-raw-data_bceaaesdslake2_dfs_core_windows_net],
    LOCATION = N'eMinerva/Module.parquet',
    FILE_FORMAT = [SynapseParquetFormat],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );
GO

