CREATE EXTERNAL TABLE [emin].[nhPerson] (
    [Title] NVARCHAR (4000) NULL,
    [FamName] NVARCHAR (4000) NULL,
    [FirstName] NVARCHAR (4000) NULL,
    [SecName] NVARCHAR (4000) NULL,
    [PrefName] NVARCHAR (4000) NULL,
    [PrevNames] NVARCHAR (4000) NULL,
    [DOB] DATETIME2 (7) NULL,
    [Gender] NVARCHAR (4000) NULL,
    [Religion] NVARCHAR (4000) NULL,
    [TFN] NVARCHAR (4000) NULL,
    [Nationality] NVARCHAR (4000) NULL,
    [Citizenship] NVARCHAR (4000) NULL,
    [CitizenCountry] NVARCHAR (4000) NULL,
    [CountryOfBirth] NVARCHAR (4000) NULL,
    [Ethnicity1] NVARCHAR (4000) NULL,
    [Ethnicity2] NVARCHAR (4000) NULL,
    [Ethnicity3] NVARCHAR (4000) NULL,
    [Iwi1] NVARCHAR (4000) NULL,
    [Iwi2] NVARCHAR (4000) NULL,
    [Iwi3] NVARCHAR (4000) NULL,
    [MotherTongue] NVARCHAR (4000) NULL,
    [LangAtHome] NVARCHAR (4000) NULL,
    [PacificLanguage] NVARCHAR (4000) NULL,
    [DeceasedDate] DATETIME2 (7) NULL,
    [DeathReportedBy] NVARCHAR (4000) NULL,
    [DeathReportedDate] DATETIME2 (7) NULL,
    [isStudent] BIT NULL,
    [isAcStaff] BIT NULL,
    [InterpreterRequired] BIT NULL,
    [EmploymentType] NVARCHAR (4000) NULL,
    [HighestSchoolLevel] NVARCHAR (4000) NULL,
    [HighestQualificationLevel] NVARCHAR (4000) NULL,
    [fwCreatedBy] NVARCHAR (4000) NULL,
    [fwUpdatedBy] NVARCHAR (4000) NULL,
    [fwCreated] DATETIME2 (7) NULL,
    [fwUpdated] DATETIME2 (7) NULL,
    [DebtorNo] INT NULL,
    [LastSuccessfulFinancialExport] DATETIME2 (7) NULL,
    [EntityID] INT NULL,
    [OtherLanguage] NVARCHAR (4000) NULL,
    [Login] NVARCHAR (4000) NULL,
    [DateBapCertSigned] DATETIME2 (7) NULL,
    [ParishBaptism] NVARCHAR (4000) NULL,
    [PassportCountry] NVARCHAR (4000) NULL,
    [PrefFamName] NVARCHAR (4000) NULL,
    [Occupation] NVARCHAR (4000) NULL,
    [Workplace] NVARCHAR (4000) NULL,
    [Talents] NVARCHAR (4000) NULL,
    [Interests] NVARCHAR (4000) NULL,
    [Comments] NVARCHAR (4000) NULL,
    [TownOfBirth] NVARCHAR (4000) NULL,
    [ApplicationId] INT NULL,
    [ChangeStart] DATETIME2 (7) NULL,
    [ChangeEnd] DATETIME2 (7) NULL,
    [isDisabled] BIT NULL
)
    WITH (
    DATA_SOURCE = [sds-raw-data_bceaaesdslake2_dfs_core_windows_net],
    LOCATION = N'eMinerva/nhPerson.parquet',
    FILE_FORMAT = [SynapseParquetFormat],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );
GO

