CREATE EXTERNAL TABLE [emin].[User] (
    [EmailAddress] NVARCHAR (4000) NULL,
    [FirstName] NVARCHAR (4000) NULL,
    [Surname] NVARCHAR (4000) NULL,
    [TotalLogins] INT NULL,
    [LastLogin] DATETIME2 (7) NULL,
    [InitialRole] NVARCHAR (4000) NULL,
    [CustomerCode] NVARCHAR (4000) NULL,
    [Staging] INT NULL,
    [AllowStaging] INT NULL,
    [CurrentOrderNumber] INT NULL,
    [ConfirmPassword] NVARCHAR (4000) NULL,
    [Birthday] DATETIME2 (7) NULL,
    [PhoneNumber] NVARCHAR (4000) NULL,
    [OrderEnquiryRange] INT NULL,
    [OrderEntryLines] INT NULL,
    [DisplayHeaderGraphics] INT NULL,
    [DisplayHelp] INT NULL,
    [OptimizeScreen] NVARCHAR (4000) NULL,
    [DisplayOrderEntryAvail] INT NULL,
    [RecordsPerPage] INT NULL,
    [OrderLimit] NUMERIC (18, 2) NULL,
    [OrdersApprovedBy] NVARCHAR (4000) NULL,
    [AccountAdministrator] INT NULL,
    [DeliveryInstructions] NVARCHAR (4000) NULL,
    [DeliveryAddress1] NVARCHAR (4000) NULL,
    [DeliveryAddress2] NVARCHAR (4000) NULL,
    [DeliveryAddress3] NVARCHAR (4000) NULL,
    [DeliveryAddress4] NVARCHAR (4000) NULL,
    [DeliveryPostcode] NVARCHAR (4000) NULL,
    [RepCode] NVARCHAR (4000) NULL,
    [DisplayGridGraphics] INT NULL,
    [DisplayTemplateGraphics] INT NULL,
    [UserGroup] NVARCHAR (4000) NULL,
    [Faxnumber] NVARCHAR (4000) NULL,
    [Nactive] INT NULL,
    [Billinguser] INT NULL,
    [Language] NVARCHAR (4000) NULL,
    [WorkplaceChange] INT NULL,
    [ShortName] NVARCHAR (4000) NULL,
    [fwCreated] DATETIME2 (7) NULL,
    [fwCreatedBy] NVARCHAR (4000) NULL,
    [fwUpdated] DATETIME2 (7) NULL,
    [fwUpdatedBy] NVARCHAR (4000) NULL,
    [DiaryDays] INT NULL,
    [Starttime] DATETIME2 (7) NULL,
    [Endtime] DATETIME2 (7) NULL,
    [RestrictLoginHours] INT NULL,
    [InterestedCategories] NVARCHAR (4000) NULL,
    [DateFormat] NVARCHAR (4000) NULL,
    [TimeFormat] NVARCHAR (4000) NULL,
    [FontSize] NVARCHAR (4000) NULL,
    [Password] NVARCHAR (4000) NULL,
    [DomainUsername] NVARCHAR (4000) NULL,
    [FailedLogins] INT NULL,
    [PW1] NVARCHAR (4000) NULL,
    [PW2] NVARCHAR (4000) NULL,
    [PW3] NVARCHAR (4000) NULL,
    [PW4] NVARCHAR (4000) NULL,
    [PW5] NVARCHAR (4000) NULL,
    [PWExpiry] INT NULL,
    [PWUpdateDate] DATETIME2 (7) NULL,
    [DefaultCampus] NVARCHAR (4000) NULL,
    [StaffID] NVARCHAR (4000) NULL,
    [BusinessRole] NVARCHAR (4000) NULL,
    [Admin] NVARCHAR (4000) NULL,
    [StartPage] NVARCHAR (4000) NULL,
    [ExternalID] NVARCHAR (4000) NULL,
    [StaffEntityID] INT NULL,
    [DiaryDaysBefore] INT NULL,
    [ISADefaultTab] NVARCHAR (4000) NULL,
    [USSDefaultPage] NVARCHAR (4000) NULL,
    [AdUsername] NVARCHAR (4000) NULL
)
    WITH (
    DATA_SOURCE = [sds-raw-data_bceaaesdslake2_dfs_core_windows_net],
    LOCATION = N'eMinerva/User.parquet',
    FILE_FORMAT = [SynapseParquetFormat],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );
GO

